stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
    - dotnet publish --configuration Release --output $OUTPUT_DIR
  artifacts:
    paths:
      - $OUTPUT_DIR
    expire_in: 2 days

deploy:
  stage: deploy
  image: curlimages/curl:latest
  dependencies:
    - build
  script:
    - echo "Deploying to VPS"
    - curl -T "$OUTPUT_DIR/*" ftp://$VPS_USER:$VPS_PASSWORD@$VPS_HOST/path/to/deploy/ --ftp-create-dirs
    - echo "Deployment completed"