stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind

build:
  stage: build
  tags:
    - api
  script:
    - docker load < sanandres_api.tar
    - if [ "$(docker ps -q -f name=san-andres-api)" ]; then docker stop san-andres-api; fi
    - if [ "$(docker ps -aq -f name=san-andres-api)" ]; then docker rm san-andres-api; fi
    - docker run -d --name san-andres-api -p $PORT_API:8080 sanandres_api:latest
  artifacts:
    paths:
      - sanandres_api.tar

deploy:
  stage: deploy
  tags:
    - api
  script:
    - docker load < sanandres_api.tar
    - docker stop san-andres-api || true
    - docker rm san-andres-api || true
    - docker run -d --name san-andres-api -p $PORT_API:8080 sanandres_api:latest
