stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t sanandres_api:latest .
    - docker save sanandres_api:latest > sanandres_api.tar
  artifacts:
    paths:
      - sanandres_api.tar

deploy:
  stage: deploy
  script:
    - docker load < sanandres_api.tar
    - docker stop san-andres-api || true
    - docker rm san-andres-api || true
    - docker run -d --name san-andres-api -p $PORT_API:8080 sanandres_api:latest
