trigger:
- main

pool:
  name: Default 

steps:
- script: |
    echo "¡Hola desde el VPS!"
    echo "Estoy ejecutándome en el agente: $(Agent.Name)"
    echo "Ruta del trabajo: $(Pipeline.Workspace)"
  displayName: 'Saludo y verificación'