trigger:
- main

pool:
  name: Default 

variables:
  DOCKER_IMAGE_NAME: 'sanandres_api'
  DOCKER_NETWORK: 'san_andres'
  PORT: '5000:8080'
  ENVIRONMENT: 'Development'
  
steps:
  # Paso 1: Checkout oficial en lugar de git pull
  - checkout: self
    clean: true 
    fetchDepth: 1  # Solo el último commit para mayor velocidad

  # Paso 2: Build de Docker
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      repository: $(DOCKER_IMAGE_NAME)
      dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags: latest

  # Paso 3: Parar y eliminar contenedor existente
  - script: |
      docker stop $(DOCKER_IMAGE_NAME) || true
      docker rm -v $(DOCKER_IMAGE_NAME) || true
    displayName: 'Remove existing container'

  # Paso 4: Ejecutar nuevo contenedor
  - script: |
      docker run -d \
        -p $(PORT) \
        --network $(DOCKER_NETWORK) \
        -e ASPNETCORE_ENVIRONMENT=$(ENVIRONMENT) \
        -e ConnectionStrings__DefaultConnection="$(POSTGRES_CONNECTION_STRING)" \
        --name $(DOCKER_IMAGE_NAME) \
        $(DOCKER_IMAGE_NAME):latest
    displayName: 'Run Docker container'
    env:
      POSTGRES_CONNECTION_STRING: $(POSTGRES_CONNECTION_STRING)