using SanAndres_Api.Models;

namespace SanAndres_Api.Database.Seeders
{
  public static class AutopartsBrandSeed
  {
    public static List<AutopartBrand> GetSeed() =>
      new List<AutopartBrand>{
        new AutopartBrand { Id = 1, Name = "Yoitoki" , Logo = "" },
        new AutopartBrand { Id = 2, Name = "Perfect" , Logo = "" },
        new AutopartBrand { Id = 3, Name = "Nissan" , Logo = "" },
        new AutopartBrand { Id = 4, Name = "Bosch" , Logo = "" },
        new AutopartBrand { Id = 5, Name = "Denso" , Logo = "" },
        new AutopartBrand { Id = 6, Name = "Hibari" , Logo = "" },
        new AutopartBrand { Id = 7, Name = "Koyo" , Logo = "" },
        new AutopartBrand { Id = 8, Name = "KYB" , Logo = "" },
        new AutopartBrand { Id = 9, Name = "MAHLE" , Logo = "" },
        new AutopartBrand { Id = 10, Name = "Mando" , Logo = "" },
        new AutopartBrand { Id = 11, Name = "NPC" , Logo = "" },
        new AutopartBrand { Id = 12, Name = "PHC" , Logo = "" },
        new AutopartBrand { Id = 13, Name = "RIK" , Logo = "" },
        new AutopartBrand { Id = 14, Name = "SACHS" , Logo = "" },
        new AutopartBrand { Id = 15, Name = "SCHAEFFLER" , Logo = "" },
        new AutopartBrand { Id = 16, Name = "Shibumi" , Logo = "" },
        new AutopartBrand { Id = 17, Name = "Toto Pistons" , Logo = "" },
        new AutopartBrand { Id = 18, Name = "YUASA" , Logo = "" },
        new AutopartBrand { Id = 19, Name = "GMB" , Logo = "" },
        new AutopartBrand { Id = 20, Name = "OSK" , Logo = "" },
        new AutopartBrand { Id = 21, Name = "PHILIPS" , Logo = "" },
        new AutopartBrand { Id = 22, Name = "SKF" , Logo = "" },
        new AutopartBrand { Id = 23, Name = "TBK" , Logo = "" },
        new AutopartBrand { Id = 24, Name = "OIL PUMP" , Logo = "" },
        new AutopartBrand { Id = 25, Name = "Wolf" , Logo = "" },
        new AutopartBrand { Id = 26, Name = "Mitsubishi" , Logo = "" },
        new AutopartBrand { Id = 27, Name = "Aisin" , Logo = "" },
        new AutopartBrand { Id = 28, Name = "Mann-Filter" , Logo = "" },
        new AutopartBrand { Id = 29, Name = "Wix" , Logo = "" },
        new AutopartBrand { Id = 30, Name = "Fram" , Logo = "" },
        new AutopartBrand { Id = 31, Name = "NGK" , Logo = "" },
        new AutopartBrand { Id = 32, Name = "Hitachi" , Logo = "" },
        new AutopartBrand { Id = 33, Name = "TRW" , Logo = "" },
        new AutopartBrand { Id = 34, Name = "Valeo" , Logo = "" },
        new AutopartBrand { Id = 35, Name = "Delphi" , Logo = "" },
        new AutopartBrand { Id = 36, Name = "Mevotech" , Logo = "" },
        new AutopartBrand { Id = 37, Name = "Corteco" , Logo = "" },
        new AutopartBrand { Id = 38, Name = "Timken" , Logo = "" },
        new AutopartBrand { Id = 39, Name = "ZF" , Logo = "" },
        new AutopartBrand { Id = 40, Name = "Federal Mogul" , Logo = "" },
        new AutopartBrand { Id = 41, Name = "Gates" , Logo = "" },
        new AutopartBrand { Id = 42, Name = "Bando" , Logo = "" },
        new AutopartBrand { Id = 43, Name = "Dayco" , Logo = "" },
        new AutopartBrand { Id = 44, Name = "Pirelli" , Logo = "" },
        new AutopartBrand { Id = 45, Name = "Firestone" , Logo = "" },
        new AutopartBrand { Id = 46, Name = "Bridgestone" , Logo = "" },
        new AutopartBrand { Id = 47, Name = "Goodyear" , Logo = "" },
        new AutopartBrand { Id = 48, Name = "Yokohama" , Logo = "" },
        new AutopartBrand { Id = 49, Name = "Maxxis" , Logo = "" },
        new AutopartBrand { Id = 50, Name = "Toyo" , Logo = "" },
        new AutopartBrand { Id = 51, Name = "Falken" , Logo = "" },
        new AutopartBrand { Id = 52, Name = "Avon" , Logo = "" },
        new AutopartBrand { Id = 53, Name = "Kenda" , Logo = "" },
        new AutopartBrand { Id = 54, Name = "Michelin" , Logo = "" },
        new AutopartBrand { Id = 55, Name = "Continental" , Logo = "" },
        new AutopartBrand { Id = 56, Name = "BKT" , Logo = "" },
        new AutopartBrand { Id = 57, Name = "Trelleborg" , Logo = "" },
        new AutopartBrand { Id = 58, Name = "Uniroyal" , Logo = "" },
        new AutopartBrand { Id = 59, Name = "Kumho" , Logo = "" },
        new AutopartBrand { Id = 60, Name = "Hankook" , Logo = "" },
        new AutopartBrand { Id = 61, Name = "Cooper" , Logo = "" },
        new AutopartBrand { Id = 62, Name = "Nitto" , Logo = "" },
        new AutopartBrand { Id = 63, Name = "Wabco" , Logo = "" },
        new AutopartBrand { Id = 64, Name = "Haldex" , Logo = "" },
        new AutopartBrand { Id = 65, Name = "Spicer" , Logo = "" },
        new AutopartBrand { Id = 66, Name = "VDO" , Logo = "" },
        new AutopartBrand { Id = 67, Name = "Mann" , Logo = "" },
        new AutopartBrand { Id = 68, Name = "Lucas" , Logo = "" },
        new AutopartBrand { Id = 69, Name = "Sylvania" , Logo = "" },
        new AutopartBrand { Id = 70, Name = "Behr" , Logo = "" },
        new AutopartBrand { Id = 71, Name = "Optima" , Logo = "" },
        new AutopartBrand { Id = 72, Name = "Exide" , Logo = "" },
        new AutopartBrand { Id = 73, Name = "Interstate" , Logo = "" },
        new AutopartBrand { Id = 74, Name = "GPC" , Logo = "" },
        new AutopartBrand { Id = 75, Name = "Tukisumi" , Logo = "" },
      };
    }
}